/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'seamark' at '16/10/13 11:02' with Gradle 3.1
 *
 * @author seamark, @date 16/10/13 11:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
